# Generated by Django 3.2.19 on 2023-06-28 13:37

import django.core.validators
from django.db import migrations, models
import myplant.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20230628_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(20), myplant.web.validators.validate_contains_only_letters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=20, validators=[myplant.web.validators.validate_capitalized]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=20, validators=[myplant.web.validators.validate_capitalized]),
        ),
    ]
